version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports: 
      - "6379:6379"

  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets 
      - ${HOME}/.aspnet/https:/root/.aspnet/https 
    ports:
      - "8000:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Redis=basketdb:6379"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets 
      - ${HOME}/.aspnet/https:/root/.aspnet/https 
    ports:
      - "8001:80"
    depends_on:
      - basketdb

